version: "2"

services:
  service:
    image: "$name;format="norm"$/$name;format="norm"$:latest"
    command:
      - "-Dakka.cluster.seed-nodes.0=akka.tcp://$actorSystemName$@127.0.0.1:2551"
    environment:
      JSON_WEB_TOKEN_SECRET: "c2VjcmV0"
      AKKA_REMOTE_HOSTNAME: "127.0.0.1"
      SHUTDOWN_DELAY: "3s"
    ports:
      - "8080:8080"
      - "2551:2551"
